### PR TITLE
feat: add socket and notifications

### PR DESCRIPTION
**Pull request by Irek-91**

### CODE REVIEW

**Review by valek00794 — APPROVED** [review]
reviewed

**Comment by Irek-91** [comment]
run build production instagram-gateway

**Comment by Irek-91** [comment]
run build production files

**Comment by Irek-91** [comment]
run build production instagram-gateway

**Comment by Irek-91** [comment]
run build production instagram-gateway

**Comment by Irek-91** [comment]
run build production instagram-gateway

**Comment by Irek-91** [comment]
run build production payments

**Comment by Irek-91** [comment]
run build production files

**Pull request merged**
